default:
  content:
    - name: "Serving Loan Risk Predictions with FastAPI"
      path: "."
      description: "An API serving predictions from a loan risk model, built with FastAPI."
      tag:
        - "Examples|Python|FastAPI"
      url: "/python/fastapi-loan-model/"
      image: "screenshot.png"
