default:
  content:
    - name: "Penguins API"
      path: "./api"
      description: "An API serving penguin data measurements, built with Plumber."
      tag:
        - "Examples|R|Plumber"
      url: "/r/plumber-penguins/"
      image: "screenshot.png"
