default:
  content:
    - name: "Literate Programming with Quarto"
      path: "."
      description: "An open-source scientific and technical publishing system."
      tag:
        - "Examples|Python|Quarto"
      url: "/python/quarto-lightbox"
      image: "quarto-lightbox.png"
